### ISSUE TITLE
Hide item

### ISSUE THREAD

**Issue by silentcross** [jeremyknight-me/aspnet-forms-bootstrap-menu#1]
How can i hide the item ? or set the visible on one of the item ?

**Comment by jeremyknight-me** [comment]
Are you looking to secure based on roles or just programmatically turn the visibility on/off?

**Comment by silentcross** [comment]
secure based on roles
im using this method for now

> 

            foreach (var applicationPermission in q)
            {
                foreach (MenuItem menuItem in menuItems)
                {
                    if (!mu.checkPermission(iduser, applicationPermission.Name))
                    {                       
                        var subItem = menuItem.ChildItems.Cast<MenuItem>().FirstOrDefault(p => p.Value == applicationPermission.Name);
                        if (subItem != null)
                        {
                            menuItem.ChildItems.Remove(subItem);
                        }
                    }
                }
            }


the problem is if theres no child item any more how can i set the visibility for the parent ?
and is there any other method to turn the visibility ?

**Comment by jeremyknight-me** [comment]
In my opinion, it would be easier to build the menu programmatically for this scenario. Setup your menu in a in a List<MenuItem> (with children as well). Then you can loop thru them and if permissions allow add the item to the Menu.

**Comment by silentcross** [comment]
wow, thanks for the suggestion, you save my day!

**Comment by jeremyknight-me** [comment]
glad I could help
